# netlify.toml

# Esto le dice a Netlify:
# "Cualquier petición que veas a /api/...
# ...reenvíala secretamente a TMDb"

[[redirects]]
  from = "/api/*"
  to = "https://api.themoviedb.org/3/:splat"
  status = 200 # 200 significa "OK" (actúa como un proxy)